version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:15
    container_name: devjobs-postgres
    restart: always
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=root
      - POSTGRESQL_DATABASE=devjobs
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/bitnami/postgresql
    networks:
      - devjobs-network

  redis:
    image: redis:7
    container_name: devjobs-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - devjobs-network

volumes:
  postgres_data:
  redis_data:

networks:
  devjobs-network:
    driver: bridge
